import {
  createRouter,
  Router,
  Route,
  Link,
  Outlet,
  Navigate,
  useRouter,
  useParams,
  useQuery,
  useLocation,
  useRoute,
  tryUseRouter,
  createAuthGuard,
  combineGuards,
  createAsyncGuard,
  redirect,
  redirectReplace,
  buildPath,
  getQueryValue,
  pathsEqual,
  useNavigate,
  createPathHistory,
  createHashHistory,
} from "@kikojs/router"
